const colors = {
  light: {
    background: '#ffffff',
    foreground: '#1F3A5F', 
    card: '#ffffff',
    cardForeground: '#1F3A5F',
    primary: '#1595C8',
    primaryForeground: '#ffffff',
    secondary: '#E8F4FA',
    secondaryForeground: '#0C6E96',
    muted: '#F5F7FA',
    mutedForeground: '#4A5568',
    accent: '#71BF3B',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#e2e8f0',
    input: '#e2e8f0',
    stageNew: '#FFC425',
    stageContacted: '#6CB33F',
    stageProposal: '#6CADDE',
    stageNegotiation: '#820024',
    stageWon: '#00A98F',
    stageLost: '#4A5568',
  },
  dark: {
    background: '#0a0a0a',
    foreground: '#f8fafc',
    card: '#1e293b',
    cardForeground: '#f8fafc',
    primary: '#1595C8',
    primaryForeground: '#ffffff',
    secondary: '#1e293b',
    secondaryForeground: '#E8F4FA',
    muted: '#334155',
    mutedForeground: '#94a3b8',
    accent: '#71BF3B',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#334155',
    input: '#334155',
    stageNew: '#FFC425',
    stageContacted: '#6CB33F',
    stageProposal: '#6CADDE',
    stageNegotiation: '#ff4d79',
    stageWon: '#00A98F',
    stageLost: '#94a3b8',
  },
  radius: 8,
};

export default colors;
