BEGIN;
CREATE TEMP TABLE _ct(matchname text,email text,full_name text,first_name text,last_name text,title text) ON COMMIT DROP;
INSERT INTO _ct VALUES ('31 Supper Club','matt@grindgastropub.com','GM','','','GM'),
('Aden Senior Living','cgilmor@adenseniorliving.com','Cathy Gilmore','Cathy','Gilmore',''),
('Advent Health Daytona Beach','ahs.ap.documents@ahss.org','Ms Michelle Edwards','Michelle','Edwards',''),
('AdventHealth DeLand','kirkspaulding@iammorrison.com','Kirk Spaulding','Kirk','Spaulding',''),
('AdventHealth Fish Memorial','kallie.heikes@adventhealth.com','','','',''),
('AdventHealth New Smryna Beach','martindragiev@iammorrison.com','Martin Dragiev','Martin','Dragiev',''),
('AdventHealth Palm Coast','joseph.masi@adventhealth.com','Chef Joe Masi','Joe','Masi','Chef'),
('Big Tunas Beach Bar/Grill','hayaal@usa.com','Hank','Hank','',''),
('Cafe One','cafeoneormondbeach@gmail.com','','','',''),
('Cape Canaveral Hospital','peterchriste@iammorrison.com','Peter Christe','Peter','Christe',''),
('Caribbean Jack''s Rstrnt & Bar','william_funcheon@equitylifestyle.com','Chris Rachid','Chris','Rachid',''),
('Charlie Horse Restaurant','lldupree669@aol.com','Brian Moody, KM - Morning/Aft. Shift','Brian','Moody, KM - Morning/Aft. Shift',''),
('Chumley''s Depot','gbe280@gmail.com','Marcus Darnell','Marcus','Darnell',''),
('COA','accounting@coacocoabeach.com','Eric Basta','Eric','Basta',''),
('Coasters Pub','dave@coasterspub.com','David Swartz','David','Swartz',''),
('Coconuts on the Beach','additup0727@gmail.com','Angela Johnson','Angela','Johnson',''),
('Collins Aerospace','','Devin Ward','Devin','Ward',''),
('Courtyard Daytona Beach Speedway/Airport','','Shannon Dearin','Shannon','Dearin',''),
('Daytona Airport - Java Moon Restaurant','ralzeideh@faber-intl.com','GM','','','GM'),
('Daytona International Speedway/Levy','mpeterson2@levyrestaurants.com','Ryan Champagne','Ryan','Champagne',''),
('Daytona Lagoon-Ocean Walk Vlg','accounting@daytonalagoon.com','','','',''),
('Daytona State College','ma4051@metzcorp.com','TBD','','','TBD'),
('Daytona Tortugas','angelaford@daytonatortugas.com','Angela Ford','Angela','Ford',''),
('Delta Hotel','katherine.thompson@marriott.com','GM','','','GM'),
('Double Tapp Grille','ckopp@frogbones.com','Jasmine or Kristie is GM','Jasmine','or Kristie is GM',''),
('Elks Lodge - Ormond','secretary@lodge2193.org','Debbie','Debbie','',''),
('ERAU Boundless','dustin.fitch@sodexo.com','Dustin Fitch 226-7337','Dustin','Fitch 226-7337',''),
('ERAU Chick-Fil-A','kenneth.behnke@sodexo.com','Ken Behnke','Ken','Behnke',''),
('ERAU Food Truck','randall.spencer@sodexo.com','Randall Spencer','Randall','Spencer',''),
('ERAU Propellers','agreen@filta.com','Randall Spencer','Randall','Spencer',''),
('ERAU - Qdoba','randall.spencer@sodexo.com','Randall Spencer','Randall','Spencer',''),
('ERAU Refueling Station','michael.schnitzer@sodexo.com','Mike Schnitzer','Mike','Schnitzer',''),
('Florida Seafood Company','sstarvinc@yahoo.com','Stephen Stavris','Stephen','Stavris',''),
('Fugu Sushi','roberts.kirt@yahoo.com','Kirt Roberts','Kirt','Roberts',''),
('Halifax Health Deltona','luis.bernabe@halifax.org','Luis Bernabe','Luis','Bernabe',''),
('Halifax Health-France Tower','steven.botchen@halifax.org','Mr Steven Botchen','Steven','Botchen',''),
('Halifax Health','steven.botchen@halifax.org','Mr Steven Botchen','Steven','Botchen',''),
('Halifax Plantation - Tavern Restaurant','manager@halifaxplantation.com','Tom Seigler','Tom','Seigler',''),
('Hard Rock Hotel','robert.morgan@hrhdaytonabeach.com','Rob Morgan','Rob','Morgan',''),
('Hog Heaven Bar-B-Q','ashley@qsibusinesssolutions.com','Jeremy Stroud','Jeremy','Stroud',''),
('Holmes Regional Medical Center','ken.windsor@health-first.org','GM','','','GM'),
('Huey Magoos','josh@swiftconsulting-pro.com','','','',''),
('Hull''s Seafood Kitchen Rstrnt','hullsseafoodmgr@gmail.com','Mr. Brian Cavanaugh','Brian','Cavanaugh',''),
('Hyde Park Steakhouse - Daytona Beach','chefdaytona@hydeparkgrille.com','Mr. Eric Black','Eric','Black',''),
('Iron Horse Saloon','ilipsey@hotactionsw.com','Sally','Sally','',''),
('Jersey Brothers Diner','seguravivian@bellsouth.net','Miguel Segura','Miguel','Segura',''),
('Jimmy Hula''s - Melbourne','khammond@jimmyhulas.com','Kathy Hammond','Kathy','Hammond',''),
('Jimmy Hula''s','jeffm@jimmyhulas.com','','','',''),
('Jimmy Hula''s -Ormond Beach','rruss@parkerstark.com','GM','','','GM'),
('Jimmy Hulas-Port Orange','apataky@jimmyhulas.com','GM','','','GM'),
('Lenox at Merritt Island (Pacifica Residential Living)','fsd.lenoxmi@pacificaresidential.com','Eric','Eric','',''),
('Lil Mama''s','lilmamas91@yahoo.com','DeBorah','DeBorah','',''),
('Lost Lagoon Wings & Grill','lagoonone@gmail.com','Mathieu Howell','Mathieu','Howell',''),
('Luna Food and Wine','tasteofchef@gmail.com','Luca Filadi','Luca','Filadi',''),
('Melbourne Regional Hospital','williamcoleman@iammorrison.com','William Coleman','William','Coleman',''),
('Mel''s Tiki Cafe','melstikicafe@gmail.com','Melanie Pitcher','Melanie','Pitcher',''),
('Merk''s Bar and Grill','bobnmlcolvin@gmail.com','GM','','','GM'),
('Moose Lodge - Ormond','lodge1263@mooseunits.org','Jack Rafool','Jack','Rafool',''),
('Murph''s Patio Bar/Grill','wgalloway0228@gmail.com','Justin','Justin','',''),
('New Smyrna Speedway','newsmyrnaspeedway@gmail.com','','','',''),
('Nice & Easy Oyster Bar & Grill','niceneasyoyster@gmail.com','Jay Patel','Jay','Patel',''),
('Nolan''s Irish Pub','johnny@nolansirishpub.net','Johnny Nolan','Johnny','Nolan',''),
('Northrop Grumman','mary.rhinehardt@compass-usa.com','Mary Rhinehardt','Mary','Rhinehardt',''),
('Ocean Breeze Bar & Grill','hayden@oceanbreezebarandgrillnsb.com','Hayden Haddox','Hayden','Haddox',''),
('Oyster Pub','theoysterpub@gmail.com','GM','','','GM'),
('Palm Bay Hospital','kevin.hummel@sodexo.com','Director F&B','','','Director F&B'),
('Palm Shores Bistro','jmkappy5@yahoo.com','Jeff Kaplan','Jeff','Kaplan',''),
('Parrish Medical Center (HHS)','shawn.newberry@parrishmed.com','John Andescavage','John','Andescavage',''),
('Pineapples','officemgr@pineapplesegad.com','Mike Brennan','Mike','Brennan',''),
('Pocket and Putters','sonny@pocketsandputters.com','Sonny Barrett','Sonny','Barrett',''),
('Prost!','deb@dunesbrewing.com','Deb','Deb','',''),
('RipTides','sflaherty@riptidesrawbar.com','Mr. Rodney Hower','Rodney','Hower',''),
('Rising Tide Tap and Table','tim@risingtidetap.com','','','',''),
('Rose Villa','rosevillarestaurant@gmail.com','GM','','','GM'),
('Sea Pines Rehabilitation Hospital','gilberto.ortiz@cci-hg.com','Gilberto Ortiz','Gilberto','Ortiz',''),
('Sonny''s BBQ-Orange City','bbqorangecity@yahoo.com','Tamara','Tamara','',''),
('Sonny''s BBQ-Port Orange','bbqportorange@yahoo.com','Paul Bennett','Paul','Bennett',''),
('SpaceX','steven.king@spacex.com','Steven King','Steven','King',''),
('SpaceX - Burger Food Truck','steven.king@spacex.com','Steven King','Steven','King',''),
('SpaceX-Taco Food Truck','steven.king@spacex.com','Steven King','Steven','King',''),
('Squid Lips - Cocoa Beach','don@squidlipsgrill.com','Don Martin','Don','Martin',''),
('Squid Lips FC - Cocoa Beach','don@squidlipsgrill.com','Don Martin','Don','Martin',''),
('Squid Lips - Melbourne','tommy@squidlipsgrill.com','Tommy Greene','Tommy','Greene',''),
('Steak n Shake - New Haven','henryl@steaknshake.com','Oscar Gonzalez','Oscar','Gonzalez',''),
('Stetson University','henry.oneal@compass-usa.com','Exec Chef','','','Exec Chef'),
('The Beach Bucket','owner@thebeachbucket.com','Myre','Myre','',''),
('The Canopy at Hickory Creek','d.kuzma@allegroliving.com','Amy Turley','Amy','Turley',''),
('The Filling Cafe','thefillingstationcafecocoafl@gmail.com','Doug Ostroff','Doug','Ostroff',''),
('The Funnel King','marlenebalogh@gmail.com','Marlene Balogh','Marlene','Balogh',''),
('The Pig and Whistle','thepigcocoabeach@gmail.com','Mick Graham','Mick','Graham',''),
('Tipsy Tavern','clvorhees68@yahoo.com','Chris Vorhees','Chris','Vorhees',''),
('TNT BBQ and Grill','paulsvcwholesale@aol.com','Paul Novick','Paul','Novick',''),
('Tropics Cocktail Bar','scott.levy@tropiccocktailbar.com','Scott Levy','Scott','Levy',''),
('VFW Post 4534','post4534qm@gmail.com','Ron Hemple','Ron','Hemple',''),
('Viera Hospital','angelagutierrez@iammorrison.com','Angela Gutierrez','Angela','Gutierrez',''),
('Village Cafe','village@cobscafe.com','Alejandro','Alejandro','',''),
('Walk-Ons Sports Bistreaux','viera@walkons.com','Teddy Hines','Teddy','Hines',''),
('Whole Foods - Viera','timothy.martin@wholefoods.com','Tim Martin','Tim','Martin',''),
('Winola Farm Grocery and Deli','chefjohnny@winolafarmmeat.com','Johnny Warren','Johnny','Warren',''),
('Wyndham Ocean Walk','acctgoceanwalk@wyn.com','GM','','','GM'),
('Wyndham Ocean Walk - Pool Bar','acctgoceanwalk@wyn.com','GM','','','GM');
UPDATE contacts c SET email=COALESCE(NULLIF(t.email,''),c.email), full_name=COALESCE(NULLIF(t.full_name,''),c.full_name),
  first_name=CASE WHEN t.first_name<>'' THEN t.first_name ELSE c.first_name END, last_name=CASE WHEN t.last_name<>'' THEN t.last_name ELSE c.last_name END,
  title=COALESCE(NULLIF(t.title,''),c.title), updated_at=now()
FROM _ct t JOIN accounts a ON trim(regexp_replace(regexp_replace(regexp_replace(upper(a.company_name),'[^A-Z0-9 ]','','g'),'\y(LLC|INC|CORP|CO|COMPANY|LTD|LP|LLP|THE|OF)\y','','g'),'\s+',' ','g'))=trim(regexp_replace(regexp_replace(regexp_replace(upper(t.matchname),'[^A-Z0-9 ]','','g'),'\y(LLC|INC|CORP|CO|COMPANY|LTD|LP|LLP|THE|OF)\y','','g'),'\s+',' ','g')) AND a.deleted_at IS NULL
WHERE c.account_id=a.id AND c.is_primary=true AND c.deleted_at IS NULL;
INSERT INTO contacts (account_id,first_name,last_name,full_name,title,email,is_primary)
SELECT DISTINCT ON (a.id) a.id, NULLIF(t.first_name,''),NULLIF(t.last_name,''),NULLIF(t.full_name,''),NULLIF(t.title,''),NULLIF(t.email,''),true
FROM _ct t JOIN accounts a ON trim(regexp_replace(regexp_replace(regexp_replace(upper(a.company_name),'[^A-Z0-9 ]','','g'),'\y(LLC|INC|CORP|CO|COMPANY|LTD|LP|LLP|THE|OF)\y','','g'),'\s+',' ','g'))=trim(regexp_replace(regexp_replace(regexp_replace(upper(t.matchname),'[^A-Z0-9 ]','','g'),'\y(LLC|INC|CORP|CO|COMPANY|LTD|LP|LLP|THE|OF)\y','','g'),'\s+',' ','g')) AND a.deleted_at IS NULL
WHERE NOT EXISTS (SELECT 1 FROM contacts c WHERE c.account_id=a.id AND c.is_primary=true AND c.deleted_at IS NULL) ORDER BY a.id;
SELECT count(*) matched FROM _ct t WHERE EXISTS (SELECT 1 FROM accounts a WHERE trim(regexp_replace(regexp_replace(regexp_replace(upper(a.company_name),'[^A-Z0-9 ]','','g'),'\y(LLC|INC|CORP|CO|COMPANY|LTD|LP|LLP|THE|OF)\y','','g'),'\s+',' ','g'))=trim(regexp_replace(regexp_replace(regexp_replace(upper(t.matchname),'[^A-Z0-9 ]','','g'),'\y(LLC|INC|CORP|CO|COMPANY|LTD|LP|LLP|THE|OF)\y','','g'),'\s+',' ','g')) AND a.deleted_at IS NULL);
COMMIT;
